= Dokumentation Leonie / 22-23 / 4bhitm / ITP
Peter Klose, Mona Angerer, David Thaller, Al Sabagh Abdulrahman
1.0.0, {docdate}: Informationstechnische Projekte
ifndef::imagesdir[:imagesdir: images]
//:toc-placement!:  // prevents the generation of the doc at this position, so it can be printed afterwards
:sourcedir: ../src/main/java
:icons: font
:sectnums:    // Nummerierung der Überschriften / section numbering
:toc: left

//Need this blank line after ifdef, don't know why...
ifdef::backend-html5[]

// print the toc here (not at the default position)
//toc::[]


== Notes

* Leonie 2D Frontend (wie kommen die Antworten zum Benutzer)
* Wie funktioniert das trainieren eines neuronales models mit rasa generell (so ca. was sind intents, entities, stories, responses)
* Leonie 2D Dashboard (wie kann ein administrator sich die Konversationen anschauen, filtern und bearbeiten) (wie funktioniert das trainierren eines Rasa models mithilfe der Dashboard)
* Leonie 2D Deployment (wie deployen wir die teile woraus die 2D Leonie besteht? frontend, backend, dashboard, action-server, rasa-endpoint, postgres db)

== Usecase diagrams
[plantuml,admin-ucd.puml,png]
----
include::plantuml/admin-ucd.puml[]
----

[plantuml,school-ucd.puml,png]
----
include::plantuml/school-ucd.puml[]
----

[plantuml,user-ucd.puml,png]
----
include::plantuml/user-ucd.puml[]
----


== Aufgabe 15-11-22
Nächstes mal Leonie Starten können
Erklären der RASA Architektur und der vorhandenen Repo Struktur - ink Doku über diese Steps ned komplette Doku über des ganze Projekt

== Rasa Installieren Ubuntu
.At first to install Rasa on Ubuntu, a modern python version must be installed:
[source,shell]
----
sudo apt update
sudo apt install python3-dev python3
python3 --version
pip3 --version
----

.Now we create a folder ("rasaprojects") and install python3-pip, so we can install the python packages:
[source,shell]
----
mkdir rasaprojects
cd rasaprojects
sudo apt install python3-venv
----
.After that we can create a virtual environment:
[source,shell]
----
python3 -m venv ./venv
----
With our virtual environment we can now activate it and install Rasa.

.Source the virtualenv:
[source,shell]
----
source ./venv/bin/activate
----

.Install Rasa and upgrade pip:
[source,shell]
----
python -m pip install --upgrade pip rasa
----
Now our python points to the virtualenv.

.The following command should be possible:
[source,shell]
----
python -m rasa --help
python -m rasa init
----
