@startuml
left to right direction
actor "school" as fc
rectangle Leonie-Chatbot {
  usecase " Potentielle Fragen von Schülern und Eltern beantworten" as UC1
  usecase " die Leonie als Produkt Präsentieren" as UC2
  usecase "den Schulalltag veranschaulichen" as UC3
}
fc -- UC1
fc -- UC2
fc -- UC3
@enduml


